route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'slack-notifications'
receivers:
  - name: 'slack-notifications'
    slack_configs:
      - send_resolved: true
        username: 'alertmanager'
        channel: '#alertmanager'
        api_url: 'https://hooks.slack.com/services/YOUR/WEBHOOK/URL'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
