groups:
  - name: demo-service-alerts
    rules:
      - alert: HighCount5xxErrors
        expr: |
            sum by(path, instance, job) (
              increase(http_server_requests_seconds_count{status=~"5..",job="alerting-demo"}[1m])
            ) > 3
        for: 1m
        labels:
          severity: critical
        annotations:
          description: "The 5xx error rate for path {{$labels.path}} on {{$labels.instance}} is {{$value}}%."